### PR TITLE
Adds a Dutch translation

### PR DESCRIPTION
**Pull request by Tijs-B**
See issue https://github.com/rezemika/humanized_opening_hours/issues/13.

### CODE REVIEW

**Comment by Tijs-B** [comment]
Should be fixed now!

**Comment by rezemika** [comment]
Can you just remove the "#, fuzzy" line and change the following ones please? :)

```
"Language: nl_NL\n"

"Content-Type: text/plain; charset=utf-8\n"
```

Thank you!

**Comment by Tijs-B** [comment]
Should be fixed now, sorry for the hassle :)

**Comment by rezemika** [comment]
No problem, it's squashed! thank you! :)

**Pull request merged**
